name: walleto_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1
  animated_theme_switcher: ^2.0.10
  flutter_screenutil: ^5.9.3
  dio: ^5.4.3+1
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  font_awesome_flutter:
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - .env
